# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MacwifiCli < Formula
  desc "Drop-in airport replacement for macOS 13+. Scans Wi-Fi networks, inspects the current connection, and reads saved Keychain passwords."
  homepage "https://github.com/jaisonerick/macwifi-cli"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/jaisonerick/macwifi-cli/releases/download/v0.1.0/macwifi-cli_0.1.0_darwin_arm64.tar.gz"
    sha256 "079817b9312bff5811dcc390355268f030720ec0c1a93e5688a72a785dd8bf38"

    define_method(:install) do
      bin.install "macwifi-cli"
    end
  end

  def caveats
    <<~EOS
      macwifi-cli only supports macOS 13+ on Apple Silicon.

      The first run of `macwifi-cli scan` triggers the macOS Location
      Services prompt. Approve it to receive real BSSIDs back from
      future scans. You can review the permission any time at:
        System Settings > Privacy & Security > Location Services
    EOS
  end

  test do
    assert_match "macwifi-cli", shell_output("#{bin}/macwifi-cli help")
    assert_match version.to_s, shell_output("#{bin}/macwifi-cli version")
  end
end
