# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MacwifiCli < Formula
  desc "Drop-in airport replacement for macOS 13+. Scans Wi-Fi networks, inspects the current connection, and reads saved Keychain passwords."
  homepage "https://github.com/jaisonerick/macwifi-cli"
  version "1.0.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/jaisonerick/macwifi-cli/releases/download/v1.0.0/macwifi-cli_1.0.0_darwin_arm64.tar.gz"
    sha256 "bdfd2bec75d97529580d5af397bc8aa6072f0ecdedd8202373e3578867e91680"

    define_method(:install) do
      bin.install "macwifi-cli"
    end
  end

  def caveats
    <<~EOS
      macwifi-cli only supports macOS 13+ on Apple Silicon.

      The first run of `macwifi-cli scan` triggers the macOS Location
      Services prompt. Approve it to receive real BSSIDs back from
      future scans. You can review the permission any time at:
        System Settings > Privacy & Security > Location Services
    EOS
  end

  test do
    assert_match "macwifi-cli", shell_output("#{bin}/macwifi-cli help")
    assert_match version.to_s, shell_output("#{bin}/macwifi-cli version")
  end
end
